### ISSUE TITLE
Investigate moving from Sendgrid to Mandrill

### ISSUE THREAD

**Issue by houli** [DUCSS/ducss-site#16]
We can use our existing MailChimp account I believe. Save us having to manage another account.

**Comment by emmetbroaders** [comment]
+1 for Mandrill. Been looking at it for discourse and it's a nice system

**Comment by c-brenn** [comment]
I think this is related to #9 - using real animals

**Comment by houli** [comment]
Investigated. Real animals unnecessary. We made a sendgrid account :older_woman: :skin-tone-6:
