### ISSUE TITLE
Sub-optimal favicons

### ISSUE THREAD

**Issue by 22a** [DUCSS/ducss-site#44]
The favicons on the site don't look as good as they could. In the below image, the tab on the left is ducss.ie, the tab on the right is mee.space.
<img width="205" alt="screen shot 2016-01-30 at 18 54 44" src="https://cloud.githubusercontent.com/assets/7144173/12697776/3a049b1c-c783-11e5-8433-fb2c315b6b99.png">

**Comment by houli** [comment]
<img width="1306" alt="screen shot 2016-01-30 at 19 31 35" src="https://cloud.githubusercontent.com/assets/143868/12697955/2bd7062e-c788-11e5-85bb-cfb8c356dcc9.png">
@22a I've got a 196x196 favicon up there for super high resolutions

**Comment by 22a** [comment]
The favicons I generated a while back for the code submission server are sick and have billiontrillions of support for different devices, it's not that we need large images, it's that we need the small ones to be compressed in an accurate manner.
https://github.com/22a/Cleaner-Ducss-Judge/tree/master/www
The above were generated with my favourite: http://realfavicongenerator.net/
