### ISSUE TITLE
Dokku

### ISSUE THREAD

**Issue by houli** [DUCSS/ducss-site#5]
Migrate to our own hosted dokku on DigitalOcean

**Comment by c-brenn** [comment]
Alternative would be nxginx/apache with passenger as web/app server and use capistrano to deploy/setup. I think it would simplify the setup if someone had to do it from scratch (especially someone who isn't too familiar with rails). Should discuss which setup suits best

**Comment by 22a** [comment]
+1 for none of this dokku tomfoolery

**Comment by houli** [comment]
Honestly it's a lot simpler than configuring nginx. Running a bit late ATM but I'll show you when I get in
